-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 14:27:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LOJA_RN-VENDA-001
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LOJA_RN-VENDA-001` ;

-- -----------------------------------------------------
-- Schema LOJA_RN-VENDA-001
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LOJA_RN-VENDA-001` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema loja_rn-venda-001
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `loja_rn-venda-001` ;

-- -----------------------------------------------------
-- Schema loja_rn-venda-001
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja_rn-venda-001` DEFAULT CHARACTER SET utf8mb3 ;
USE `LOJA_RN-VENDA-001` ;

-- -----------------------------------------------------
-- Table `LOJA_RN-VENDA-001`.`tbProdutos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOJA_RN-VENDA-001`.`tbProdutos` ;

CREATE TABLE IF NOT EXISTS `LOJA_RN-VENDA-001`.`tbProdutos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `PrecoUnitario` DECIMAL NULL DEFAULT (10/2),
  `isPromocao` TINYINT(1) NULL,
  `tbClientes_idClientes` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProdutos`, `tbClientes_idClientes`, `Categoria_idCategoria`),
  CONSTRAINT `fk_tbProdutos_tbClientes1`
    FOREIGN KEY (`tbClientes_idClientes`)
    REFERENCES `LOJA_RN-VENDA-001`.`tbClientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProdutos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `LOJA_RN-VENDA-001`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tbProdutos_tbClientes1_idx` ON `LOJA_RN-VENDA-001`.`tbProdutos` (`tbClientes_idClientes` ASC) VISIBLE;

CREATE INDEX `fk_tbProdutos_Categoria1_idx` ON `LOJA_RN-VENDA-001`.`tbProdutos` (`Categoria_idCategoria` ASC) VISIBLE;

USE `loja_rn-venda-001` ;

-- -----------------------------------------------------
-- Table `loja_rn-venda-001`.`tbcarrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja_rn-venda-001`.`tbcarrinho` ;

CREATE TABLE IF NOT EXISTS `loja_rn-venda-001`.`tbcarrinho` (
  `idCarrinho` INT NOT NULL AUTO_INCREMENT,
  `Quantidade` VARCHAR(3) NOT NULL,
  `tbClientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idCarrinho`, `tbClientes_idClientes`),
  CONSTRAINT `fk_Carrinho_tbClientes`
    FOREIGN KEY (`tbClientes_idClientes`)
    REFERENCES `loja_rn-venda-001`.`tbclientes` (`idClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loja_rn-venda-001`.`tbcategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja_rn-venda-001`.`tbcategoria` ;

CREATE TABLE IF NOT EXISTS `loja_rn-venda-001`.`tbcategoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loja_rn-venda-001`.`tbclientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja_rn-venda-001`.`tbclientes` ;

CREATE TABLE IF NOT EXISTS `loja_rn-venda-001`.`tbclientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `Email_UNIQUE` ON `loja_rn-venda-001`.`tbclientes` (`Email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `loja_rn-venda-001`.`tbprodutos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja_rn-venda-001`.`tbprodutos` ;

CREATE TABLE IF NOT EXISTS `loja_rn-venda-001`.`tbprodutos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `PrecoUnitario` DECIMAL(10,0) NULL DEFAULT (10 / 2),
  `isPromocao` TINYINT(1) NULL DEFAULT NULL,
  `tbClientes_idClientes` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProdutos`, `tbClientes_idClientes`, `Categoria_idCategoria`),
  CONSTRAINT `fk_tbProdutos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `loja_rn-venda-001`.`tbcategoria` (`idCategoria`),
  CONSTRAINT `fk_tbProdutos_tbClientes1`
    FOREIGN KEY (`tbClientes_idClientes`)
    REFERENCES `loja_rn-venda-001`.`tbclientes` (`idClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_tbProdutos_tbClientes1_idx` ON `loja_rn-venda-001`.`tbprodutos` (`tbClientes_idClientes` ASC) VISIBLE;

CREATE INDEX `fk_tbProdutos_Categoria1_idx` ON `loja_rn-venda-001`.`tbprodutos` (`Categoria_idCategoria` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
